name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --no-audit --progress=false

      - name: Build frontend
        run: npm run build --if-present

      - name: Start server
        run: |
          node server/index.js &
          sleep 2

      - name: Smoke tests
        run: npm run smoke
